name: ScriptExec
main: com.lights0123.ScriptExec.ScriptExec
version: 0.2.8
softdepend: [Vault]
author: lights0123
website: http://dev.bukkit.org/bukkit-plugins/scriptexec
description: Execute shell commands through minecraft.
commands:
   scriptexec:
      aliases: se
      description: Reload, Execute, or get info about ScriptExec.
      usage: /se OR /se reload OR /se execute <name>
permissions:
    scriptexec.*:
        description: Gives access to all ScriptExec commands.
        children:
            scriptexec.info: true
            scriptexec.reload: true
            scriptexec.execute: true
    scriptexec.info:
        description: Allows you to view info about ScriptExec.
        default: true
    scriptexec.reload:
        description: Allows you to reload the config.
        default: op
    scriptexec.execute:
        description: Executes a script.
        default: op